"""The progress schedule: the tick script and the no-agent cron job that runs it (`hermes tailgate setup`)."""

from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

from ..tailgate_core import Source, Store, Tracker, save_settings

CRON_NAME = "tailgate"
TICK_SCRIPT = "tailgate-tick.py"
# Cron only: Hermes runs an interval such as `every 5m` five minutes after the previous run,
# checked once a minute, so intervals drift. Cron expressions land on fixed clock times.
DEFAULT_SCHEDULE = "*/5 * * * *"
PLUGIN_DIR = Path(__file__).resolve().parent.parent


def tick_script(data_dir: Path) -> str:
    return f'''# Generated by `hermes tailgate setup`; regenerate rather than edit.
# Runs as a no-agent cron job: stdout is delivered to chat verbatim, empty stdout is silent.
import os, pwd, sys
os.environ.setdefault("HOME", pwd.getpwuid(os.getuid()).pw_dir)  # hermes-agent#114209
sys.path.insert(0, {str(PLUGIN_DIR)!r})
from tailgate_core import Store, Tracker, load_settings
DATA_DIR = {str(data_dir)!r}
out = Tracker(Store(DATA_DIR), load_settings(DATA_DIR)).round()
if out:
    print(out)
'''


def hermes_cmd() -> list[str]:
    exe = shutil.which("hermes")
    return [exe] if exe else [sys.executable, "-m", "hermes_cli.main"]


def install(data_dir: Path, sources: list[Source], schedule: str, deliver: str) -> int:
    if len(schedule.split()) != 5:
        print(f"tailgate: --schedule must be a cron expression with five fields, e.g. "
              f"{DEFAULT_SCHEDULE!r}; got {schedule!r}")
        return 2
    scripts = data_dir.parent.parent / "scripts"  # <hermes home>/plugin-data/<plugin>
    scripts.mkdir(parents=True, exist_ok=True)
    (scripts / TICK_SCRIPT).write_text(tick_script(data_dir), encoding="utf-8")
    save_settings(data_dir, sources)
    known = Tracker(Store(data_dir), sources).take_baseline()
    print(f"tailgate: {known} existing job(s) recorded as history; only jobs from now on are announced.")
    # Update the job if it exists (cron verbs accept a job name), otherwise create it.
    result = subprocess.run(hermes_cmd() + ["cron", "edit", CRON_NAME, "--schedule", schedule,
                                            "--deliver", deliver], capture_output=True, text=True)
    if result.returncode != 0:
        result = subprocess.run(hermes_cmd() + ["cron", "create", schedule, "--no-agent",
                                                "--script", TICK_SCRIPT, "--deliver", deliver,
                                                "--name", CRON_NAME], capture_output=True, text=True)
    print(result.stdout.strip() or result.stderr.strip())
    if result.returncode != 0:
        return result.returncode
    print(f"tailgate: {len(sources)} source(s), schedule {schedule!r}, delivered to {deliver}.")
    if not sources:
        print("tailgate: no sources configured yet; see README (plugins.entries.tailgate.settings.sources).")
    return 0
